/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface User {
  created_by: string;
  created_on: string;
  email: string | null;
  id: string;
  instagram_handle: string | null;
  joined_at: string | null;
  name: string | null;
  tiktok_handle: string | null;
  updated_by: string;
  updated_on: string;
  user_id: string | null;
}

export interface DB {
  user: User;
}
